// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DNATesting.SoapAPIServices.NhanVT.SoapModels;
[DataContract]
public partial class ServiceCategoriesNhanVt
{
    [DataMember]

    public int? ServiceCategoryNhanVtid { get; set; }
    [DataMember]

    public string CategoryName { get; set; }
    [DataMember]

    public string Description { get; set; }
    [DataMember]

    public DateTime? CreatedDate { get; set; }
    [DataMember]

    public bool? IsActive { get; set; }
    [DataMember]

    public virtual ICollection<ServicesNhanVt> ServicesNhanVts { get; set; } = new List<ServicesNhanVt>();
}