// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace DNATesting.SoapAPIServices.NhanVT.SoapModels;

[DataContract(Namespace = "http://tempuri.org/")]
public class ServicesNhanVt
{
    [DataMember]
    public int? ServicesNhanVtid { get; set; }

    [DataMember]
    public int ServiceCategoryNhanVtid { get; set; }

    [DataMember]
    public string ServiceName { get; set; }

    [DataMember]
    public string Description { get; set; }

    [DataMember]
    public decimal? Price { get; set; }

    [DataMember]
    public int? Duration { get; set; }

    [DataMember]
    public bool? IsSelfSampleAllowed { get; set; }

    [DataMember]
    public bool? IsHomeVisitAllowed { get; set; }

    [DataMember]
    public bool? IsClinicVisitAllowed { get; set; }

    [DataMember]
    public int? ProcessingTime { get; set; }

    [DataMember]
    public DateTime? CreatedDate { get; set; }

    [DataMember]
    public DateTime? ModifiedDate { get; set; }

    [DataMember]
    public bool? IsActive { get; set; }
    //[DataMember]
    //public virtual ServiceCategoriesNhanVt ServiceCategoryNhanVt { get; set; }
}